-- ============================================================================
-- V1__initial_schema.sql
--
-- Schema inicial do Nexus Design para PostgreSQL (perfil prod).
--
-- Este DDL foi obtido materializando as entidades JPA atuais contra um
-- PostgreSQL 16 real (via Hibernate ddl-auto=create) e capturando a saida
-- exata com pg_dump --schema-only, para garantir que bate 100% com o que
-- "spring.jpa.hibernate.ddl-auto=validate" vai exigir em producao. Nao foi
-- escrito de memoria.
--
-- Nao contem NENHUM dado — apenas estrutura (tabelas, PKs, FKs, UNIQUE).
-- Dados fake/demo/credenciais NAO fazem parte desta migration (ver Fase 1).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- users: contas de acesso ao sistema.
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(255) NOT NULL,
    password       VARCHAR(255) NOT NULL,
    nome_completo  VARCHAR(255),
    email          VARCHAR(255),
    cargo          VARCHAR(255),
    role           VARCHAR(255),
    ativo          BOOLEAN,
    data_criacao   TIMESTAMP(6),
    CONSTRAINT users_username_key UNIQUE (username)
);

-- Módulos de acesso extra liberados a um usuário (@ElementCollection de User.permissoes).
CREATE TABLE user_permissoes (
    user_id    BIGINT NOT NULL REFERENCES users(id),
    permissao  VARCHAR(255)
);
CREATE INDEX idx_user_permissoes_user_id ON user_permissoes(user_id);

-- ----------------------------------------------------------------------------
-- clientes: empresas/marcas atendidas.
-- ----------------------------------------------------------------------------
CREATE TABLE clientes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(255) NOT NULL,
    segmento        VARCHAR(255),
    contato         VARCHAR(255),
    telefone        VARCHAR(255),
    email           VARCHAR(255),
    logo_url        VARCHAR(1000),
    data_cadastro   TIMESTAMP(6)
);

-- ----------------------------------------------------------------------------
-- tarefas: demandas/tarefas operacionais.
-- ----------------------------------------------------------------------------
CREATE TABLE tarefas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          VARCHAR(255) NOT NULL,
    descricao       TEXT,
    briefing        TEXT,
    loja            VARCHAR(255) NOT NULL,
    cliente_id      BIGINT, -- referência solta (sem FK): Tarefa não mapeia relacionamento JPA com Cliente
    status          VARCHAR(255) NOT NULL,
    prioridade      VARCHAR(255) NOT NULL,
    data_gravacao   DATE,
    data_entrega    DATE,
    criador_nome    VARCHAR(255),
    data_criacao    TIMESTAMP(6),
    data_conclusao  TIMESTAMP(6)
);

-- Responsáveis pela tarefa (@ElementCollection de Tarefa.responsaveis).
CREATE TABLE tarefa_responsaveis (
    tarefa_id         BIGINT NOT NULL REFERENCES tarefas(id),
    responsavel_nome  VARCHAR(255)
);
CREATE INDEX idx_tarefa_responsaveis_tarefa_id ON tarefa_responsaveis(tarefa_id);

-- Itens de checklist de uma tarefa (@OneToMany de Tarefa.checklist).
CREATE TABLE tarefa_checklist_itens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao   VARCHAR(255) NOT NULL,
    concluido   BOOLEAN,
    ordem       INTEGER,
    tarefa_id   BIGINT REFERENCES tarefas(id)
);
CREATE INDEX idx_tarefa_checklist_itens_tarefa_id ON tarefa_checklist_itens(tarefa_id);

-- ----------------------------------------------------------------------------
-- roteiros: roteiros de gravação/produção.
-- ----------------------------------------------------------------------------
CREATE TABLE roteiros (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo            VARCHAR(255) NOT NULL,
    loja              VARCHAR(255) NOT NULL,
    criador_nome      VARCHAR(255),
    data_gravacao     DATE,
    conteudo_script   TEXT,
    observacoes_set   TEXT,
    status            VARCHAR(255) NOT NULL,
    feito             BOOLEAN,
    data_criacao      TIMESTAMP(6),
    data_conclusao    TIMESTAMP(6)
);

-- ----------------------------------------------------------------------------
-- logos_clientes: repositório de logos por cliente.
-- ----------------------------------------------------------------------------
CREATE TABLE logos_clientes (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nome             VARCHAR(255) NOT NULL,
    variante                 VARCHAR(255),
    formato                  VARCHAR(255),
    arquivo_url_ou_base64    TEXT,
    tamanho                  VARCHAR(255),
    cor_primaria             VARCHAR(255),
    data_upload              TIMESTAMP(6)
);

-- ----------------------------------------------------------------------------
-- eventos + fotos_eventos: eventos cobertos e fotos vendidas.
-- ----------------------------------------------------------------------------
CREATE TABLE eventos (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                  VARCHAR(255) NOT NULL,
    localizacao           VARCHAR(255),
    data_evento           DATE,
    horario               VARCHAR(255),
    preco_foto_vendida    NUMERIC(38,2),
    publico_estimado      INTEGER,
    banner_url            TEXT,
    descricao             TEXT,
    status                VARCHAR(255),
    data_criacao          TIMESTAMP(6)
);

CREATE TABLE fotos_eventos (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_foto          VARCHAR(255),
    titulo               VARCHAR(255),
    url_ou_base64        TEXT,
    preco                NUMERIC(38,2),
    marca_dagua_texto    VARCHAR(255),
    visualizacoes        INTEGER,
    vendas               INTEGER,
    evento_id            BIGINT REFERENCES eventos(id),
    data_upload          TIMESTAMP(6)
);
CREATE INDEX idx_fotos_eventos_evento_id ON fotos_eventos(evento_id);

-- ----------------------------------------------------------------------------
-- vendas_fotos: vendas de fotos de eventos.
-- ----------------------------------------------------------------------------
CREATE TABLE vendas_fotos (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_venda             VARCHAR(255),
    cliente_nome             VARCHAR(255),
    cliente_email            VARCHAR(255),
    evento_nome              VARCHAR(255),
    qtd_fotos                INTEGER,
    qtd_videos               INTEGER,
    valor_total              NUMERIC(38,2) NOT NULL,
    status                   VARCHAR(255) NOT NULL,
    data_disponivel_info     VARCHAR(255),
    data_venda               TIMESTAMP(6),
    CONSTRAINT vendas_fotos_codigo_venda_key UNIQUE (codigo_venda)
);

-- ----------------------------------------------------------------------------
-- despesas: despesas operacionais.
-- ----------------------------------------------------------------------------
CREATE TABLE despesas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao         VARCHAR(255) NOT NULL,
    categoria         VARCHAR(255) NOT NULL,
    valor             NUMERIC(38,2) NOT NULL,
    data_despesa      DATE NOT NULL,
    forma_pagamento   VARCHAR(255),
    status            VARCHAR(255) NOT NULL,
    observacoes       VARCHAR(255),
    data_registro     TIMESTAMP(6)
);

-- ----------------------------------------------------------------------------
-- avaliacoes: depoimentos de clientes exibidos na landing page.
-- ----------------------------------------------------------------------------
CREATE TABLE avaliacoes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nome    VARCHAR(255) NOT NULL,
    cargo_empresa   VARCHAR(255),
    texto           TEXT NOT NULL,
    nota            INTEGER,
    ativo           BOOLEAN,
    data_criacao    TIMESTAMP(6)
);
