-- ============================================================================
-- V2__add_multitenancy.sql   (Fase 3 — Multitenancy)
--
-- Migration INCREMENTAL sobre o V1 (o V1 não é alterado). Estratégia: um único
-- banco, dados de negócio separados por tenant_id ("shared database, shared
-- schema"). O tenant de cada requisição vem do usuário autenticado no
-- backend — este script só garante integridade estrutural.
--
-- NÃO insere nenhum tenant: nenhuma empresa real ou fictícia é criada aqui.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Guarda de segurança: as colunas tenant_id abaixo são NOT NULL e o script
-- jamais inventa um dono para dados pré-existentes. Se alguma tabela de
-- negócio já tiver linhas (o que não deve ocorrer: produção nunca recebeu
-- dados de negócio), a migration aborta com uma mensagem clara em vez de
-- atribuir dados a um tenant arbitrário.
-- ----------------------------------------------------------------------------
DO $$
DECLARE
    tabela TEXT;
    total  BIGINT;
BEGIN
    FOREACH tabela IN ARRAY ARRAY[
        'clientes', 'tarefas', 'tarefa_checklist_itens', 'roteiros', 'logos_clientes',
        'eventos', 'fotos_eventos', 'vendas_fotos', 'despesas', 'avaliacoes'
    ] LOOP
        EXECUTE format('SELECT count(*) FROM %I', tabela) INTO total;
        IF total > 0 THEN
            RAISE EXCEPTION
                'V2__add_multitenancy abortada: a tabela % possui % linha(s) sem tenant. Atribua um tenant manualmente (migration de dados dedicada) antes de aplicar o V2.',
                tabela, total;
        END IF;
    END LOOP;
END $$;

-- ----------------------------------------------------------------------------
-- tenants: uma empresa cliente do SaaS (entidade ESTRUTURAL).
-- ----------------------------------------------------------------------------
CREATE TABLE tenants (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    slug           VARCHAR(255) NOT NULL,
    status         VARCHAR(255) NOT NULL,
    custom_domain  VARCHAR(255),
    created_at     TIMESTAMP(6),
    updated_at     TIMESTAMP(6),
    -- Vários NULL em custom_domain são permitidos (UNIQUE ignora NULLs no PostgreSQL).
    CONSTRAINT tenants_slug_key          UNIQUE (slug),
    CONSTRAINT tenants_custom_domain_key UNIQUE (custom_domain)
);

-- ----------------------------------------------------------------------------
-- users: NULLABLE de propósito (um futuro SUPER_ADMIN da plataforma não
-- pertence a nenhum tenant — Fase 4). Usuários de tenant sempre terão valor.
-- ----------------------------------------------------------------------------
ALTER TABLE users ADD COLUMN tenant_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
CREATE INDEX idx_users_tenant_id ON users(tenant_id);

-- ----------------------------------------------------------------------------
-- Entidades TENANT-SCOPED: tenant_id NOT NULL + FK para tenants + índice.
-- (Tabelas vazias garantido pela guarda acima, então NOT NULL sem DEFAULT.)
-- ----------------------------------------------------------------------------
ALTER TABLE clientes               ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE tarefas                ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE tarefa_checklist_itens ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE roteiros               ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE logos_clientes         ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE eventos                ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE fotos_eventos          ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE vendas_fotos           ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE despesas               ADD COLUMN tenant_id BIGINT NOT NULL;
ALTER TABLE avaliacoes             ADD COLUMN tenant_id BIGINT NOT NULL;

ALTER TABLE clientes               ADD CONSTRAINT fk_clientes_tenant               FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE tarefas                ADD CONSTRAINT fk_tarefas_tenant                FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE tarefa_checklist_itens ADD CONSTRAINT fk_tarefa_checklist_itens_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE roteiros               ADD CONSTRAINT fk_roteiros_tenant               FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE logos_clientes         ADD CONSTRAINT fk_logos_clientes_tenant         FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE eventos                ADD CONSTRAINT fk_eventos_tenant                FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE fotos_eventos          ADD CONSTRAINT fk_fotos_eventos_tenant          FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE vendas_fotos           ADD CONSTRAINT fk_vendas_fotos_tenant           FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE despesas               ADD CONSTRAINT fk_despesas_tenant               FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE avaliacoes             ADD CONSTRAINT fk_avaliacoes_tenant             FOREIGN KEY (tenant_id) REFERENCES tenants(id);

CREATE INDEX idx_clientes_tenant_id               ON clientes(tenant_id);
CREATE INDEX idx_tarefas_tenant_id                ON tarefas(tenant_id);
CREATE INDEX idx_tarefa_checklist_itens_tenant_id ON tarefa_checklist_itens(tenant_id);
CREATE INDEX idx_roteiros_tenant_id               ON roteiros(tenant_id);
CREATE INDEX idx_logos_clientes_tenant_id         ON logos_clientes(tenant_id);
CREATE INDEX idx_eventos_tenant_id                ON eventos(tenant_id);
CREATE INDEX idx_fotos_eventos_tenant_id          ON fotos_eventos(tenant_id);
CREATE INDEX idx_vendas_fotos_tenant_id           ON vendas_fotos(tenant_id);
CREATE INDEX idx_despesas_tenant_id               ON despesas(tenant_id);
CREATE INDEX idx_avaliacoes_tenant_id             ON avaliacoes(tenant_id);

-- ----------------------------------------------------------------------------
-- Integridade entre tenants (defesa em profundidade no banco): um filho NUNCA
-- pode apontar para um pai de OUTRO tenant. Feito com FK composta
-- (tenant_id, pai_id) -> pai(tenant_id, id), que exige a UNIQUE (tenant_id, id)
-- no pai. As FKs simples do V1 (filho -> pai por id) continuam existindo.
-- Colunas de referência nulas (tarefa_id/evento_id/cliente_id) não são
-- checadas (MATCH SIMPLE), como já ocorria antes.
-- ----------------------------------------------------------------------------
ALTER TABLE clientes ADD CONSTRAINT uk_clientes_tenant_id_id UNIQUE (tenant_id, id);
ALTER TABLE tarefas  ADD CONSTRAINT uk_tarefas_tenant_id_id  UNIQUE (tenant_id, id);
ALTER TABLE eventos  ADD CONSTRAINT uk_eventos_tenant_id_id  UNIQUE (tenant_id, id);

ALTER TABLE tarefa_checklist_itens
    ADD CONSTRAINT fk_tarefa_checklist_itens_tarefa_tenant
    FOREIGN KEY (tenant_id, tarefa_id) REFERENCES tarefas(tenant_id, id);

ALTER TABLE fotos_eventos
    ADD CONSTRAINT fk_fotos_eventos_evento_tenant
    FOREIGN KEY (tenant_id, evento_id) REFERENCES eventos(tenant_id, id);

-- tarefas.cliente_id era uma referência solta (sem FK) no V1. Agora, quando
-- preenchida, tem de apontar para um cliente do MESMO tenant. Ao excluir um
-- cliente, o backend (ClienteService) primeiro desvincula as tarefas do mesmo
-- tenant, mantendo o comportamento anterior de "excluir cliente nunca bloqueia".
ALTER TABLE tarefas
    ADD CONSTRAINT fk_tarefas_cliente_tenant
    FOREIGN KEY (tenant_id, cliente_id) REFERENCES clientes(tenant_id, id);

-- ----------------------------------------------------------------------------
-- vendas_fotos.codigo_venda: deixa de ser único globalmente e passa a ser
-- único POR TENANT (dois tenants podem gerar o mesmo código por coincidência).
-- ----------------------------------------------------------------------------
ALTER TABLE vendas_fotos DROP CONSTRAINT vendas_fotos_codigo_venda_key;
ALTER TABLE vendas_fotos ADD CONSTRAINT uk_vendas_fotos_tenant_codigo UNIQUE (tenant_id, codigo_venda);
