-- ============================================================================
-- V4__audit_events.sql   (Fase 4.2 — auditoria de segurança)
--
-- Trilha de auditoria APPEND-ONLY. V1..V3 são imutáveis.
--
-- DECISÕES DE DESENHO
--  * SEM chaves estrangeiras para users/tenants, de propósito: o histórico não
--    pode depender do ciclo de vida de outras linhas (nada de cascata que
--    destrua histórico, nada de FK que impeça remover/alterar usuários no futuro).
--  * SNAPSHOTS (actor_email, actor_role, actor_tenant_id, target_email): guardam
--    o estado relevante NO MOMENTO do evento; a trilha continua compreensível se
--    o usuário mudar de e-mail/role, for desativado ou removido.
--  * metadata é TEXT JSON montado SOMENTE por código tipado (allowlist de chaves e
--    valores enumerados). Nunca guarda body/headers/senha/hash/token/JWT.
--  * IMUTABILIDADE no próprio banco: triggers bloqueiam UPDATE, DELETE e TRUNCATE.
--    Observação operacional: o proprietário da tabela pode remover triggers; em
--    produção o ideal é o papel de execução da aplicação NÃO ser dono da tabela
--    (papel de migração separado), com apenas INSERT/SELECT.
-- ============================================================================

CREATE TABLE audit_events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at        TIMESTAMP(6)  NOT NULL,

    -- QUEM realizou (snapshot). actor_type: USER | SYSTEM | ANONYMOUS
    actor_type         VARCHAR(20)   NOT NULL,
    actor_user_id      BIGINT,
    actor_email        VARCHAR(254),
    actor_role         VARCHAR(20),
    actor_tenant_id    BIGINT,

    -- SOBRE quem/o quê (tenant afetado e usuário alvo; target_email é snapshot).
    target_tenant_id   BIGINT,
    target_user_id     BIGINT,
    target_email       VARCHAR(254),

    action             VARCHAR(60)   NOT NULL,
    entity_type        VARCHAR(40),
    entity_id          BIGINT,
    outcome            VARCHAR(10)   NOT NULL,

    metadata           VARCHAR(2000),
    request_ip         VARCHAR(45),
    user_agent         VARCHAR(200),

    CONSTRAINT audit_events_actor_type_chk CHECK (actor_type IN ('USER', 'SYSTEM', 'ANONYMOUS')),
    CONSTRAINT audit_events_outcome_chk    CHECK (outcome IN ('SUCCESS', 'FAILURE', 'DENIED')),
    CONSTRAINT audit_events_action_chk     CHECK (action ~ '^[A-Z][A-Z0-9_]{2,59}$'),
    CONSTRAINT audit_events_actor_role_chk CHECK (actor_role IS NULL OR actor_role IN ('SUPER_ADMIN', 'TENANT_ADMIN', 'USER')),
    -- Ator USER sempre identificado (id + snapshots); SYSTEM/ANONYMOUS nunca carregam id de usuário.
    CONSTRAINT audit_events_actor_user_chk CHECK ((actor_type = 'USER') = (actor_user_id IS NOT NULL)),
    CONSTRAINT audit_events_actor_snapshot_chk CHECK (actor_type <> 'USER' OR (actor_email IS NOT NULL AND actor_role IS NOT NULL)),
    CONSTRAINT audit_events_metadata_len_chk CHECK (metadata IS NULL OR length(metadata) <= 2000)
);

-- Consultas previstas: linha do tempo global, por tenant, por usuário (alvo/ator) e por ação.
CREATE INDEX idx_audit_events_occurred_at       ON audit_events (occurred_at DESC);
CREATE INDEX idx_audit_events_target_tenant     ON audit_events (target_tenant_id, occurred_at DESC);
CREATE INDEX idx_audit_events_target_user       ON audit_events (target_user_id, occurred_at DESC);
CREATE INDEX idx_audit_events_actor_user        ON audit_events (actor_user_id, occurred_at DESC);
CREATE INDEX idx_audit_events_action            ON audit_events (action, occurred_at DESC);

-- ----------------------------------------------------------------------------
-- APPEND-ONLY: INSERT e SELECT permitidos; UPDATE, DELETE e TRUNCATE bloqueados.
-- ----------------------------------------------------------------------------
CREATE FUNCTION audit_events_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_events é append-only: % não é permitido', TG_OP
        USING ERRCODE = 'insufficient_privilege';
END;
$$;

CREATE TRIGGER audit_events_block_update_delete
    BEFORE UPDATE OR DELETE ON audit_events
    FOR EACH ROW EXECUTE FUNCTION audit_events_append_only();

CREATE TRIGGER audit_events_block_truncate
    BEFORE TRUNCATE ON audit_events
    FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only();
