-- ============================================================================
-- V5__user_action_tokens.sql   (Fase 4.3 — tokens de recuperação de senha e convite)
--
-- Tokens de AÇÃO de uso único (PASSWORD_RESET, INVITE). V1..V4 são imutáveis.
--
--  * Só o SHA-256 do token (hex, 64 chars) é armazenado; o token puro existe
--    apenas no e-mail enviado ao usuário. Nunca é gravado, logado ou auditado.
--  * tenant_id NÃO é duplicado aqui: a posse deriva de user_id (o usuário já
--    define o tenant, ou nenhum, no caso de SUPER_ADMIN).
--  * O consumo é ATÔMICO no banco: UPDATE condicional (used_at IS NULL AND
--    revoked_at IS NULL AND expires_at > agora); apenas UMA transação vence.
--  * user_id -> ON DELETE CASCADE: excluir o usuário descarta seus tokens
--    (o histórico fica no audit_events, que não tem FK). created_by_user_id ->
--    ON DELETE SET NULL preserva o token se o administrador que convidou sumir.
-- ============================================================================

CREATE TABLE user_action_tokens (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    purpose             VARCHAR(20)  NOT NULL,
    token_hash          VARCHAR(64)  NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL,
    expires_at          TIMESTAMP(6) NOT NULL,
    used_at             TIMESTAMP(6),
    revoked_at          TIMESTAMP(6),
    requested_ip        VARCHAR(45),
    created_by_user_id  BIGINT,

    CONSTRAINT uat_token_hash_key      UNIQUE (token_hash),
    CONSTRAINT uat_user_fk             FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uat_created_by_fk       FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT uat_purpose_chk         CHECK (purpose IN ('PASSWORD_RESET', 'INVITE')),
    CONSTRAINT uat_hash_format_chk     CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT uat_expires_after_chk   CHECK (expires_at > created_at),
    -- Um token é consumido OU revogado, nunca os dois.
    CONSTRAINT uat_used_xor_revoked_chk CHECK (used_at IS NULL OR revoked_at IS NULL)
);

-- Tokens ainda ativos de um usuário/finalidade (revogação de anteriores e reenvio).
CREATE INDEX idx_uat_user_purpose_active ON user_action_tokens (user_id, purpose)
    WHERE used_at IS NULL AND revoked_at IS NULL;
-- Limpeza (expirados/usados antigos).
CREATE INDEX idx_uat_expires_at ON user_action_tokens (expires_at);
CREATE INDEX idx_uat_created_by ON user_action_tokens (created_by_user_id);
