-- V6: planos, funcionalidades comercializáveis, assinaturas, overrides por tenant e branding (Fase 4.4.1).
--
-- CONCEITOS (não confundir):
--   * features            = o que a EMPRESA pode contratar (catálogo global). NÃO são as permissions de
--                           usuário (FINANCEIRO/EQUIPE/CONFIGURACOES): a permission diz o que um USUÁRIO
--                           pode acessar DENTRO do que a empresa contratou.
--   * subscriptions.status = situação COMERCIAL. tenants.status = possibilidade OPERACIONAL de usar o SaaS.
--                           Os dois são independentes: vencimento NÃO suspende o tenant (automação futura).
--   * tenant_feature_overrides = ALLOW/DENY explícitos do SUPER_ADMIN por empresa, acima do plano.
--
-- Estas tabelas são do PLANO DE CONTROLE (administradas só por /api/admin/** e resolvidas pelo
-- EntitlementService); não são dados de negócio do tenant. Nenhuma migration anterior é alterada.
-- Nenhum plano/preço é inserido aqui; apenas o catálogo de features.

CREATE TABLE plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT plans_code_key UNIQUE (code),
    CONSTRAINT plans_code_chk CHECK (code ~ '^[A-Z][A-Z0-9_]{1,49}$')
);

CREATE TABLE features (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    -- BOOLEAN: liga/desliga. LIMIT: valor numérico (ex.: MAX_USERS, STORAGE_GB) — exige limit_value.
    kind        VARCHAR(10)  NOT NULL DEFAULT 'BOOLEAN',
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT features_code_key UNIQUE (code),
    CONSTRAINT features_code_chk CHECK (code ~ '^[A-Z][A-Z0-9_]{1,49}$'),
    CONSTRAINT features_kind_chk CHECK (kind IN ('BOOLEAN', 'LIMIT'))
);

-- Plano <-> funcionalidade (+ limite numérico opcional). Modelagem extensível: novas features/limites são
-- LINHAS, nunca colunas.
CREATE TABLE plan_features (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id     BIGINT  NOT NULL,
    feature_id  BIGINT  NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    limit_value BIGINT,
    CONSTRAINT plan_features_plan_fk    FOREIGN KEY (plan_id)    REFERENCES plans(id) ON DELETE CASCADE,
    CONSTRAINT plan_features_feature_fk FOREIGN KEY (feature_id) REFERENCES features(id),
    CONSTRAINT plan_features_unique     UNIQUE (plan_id, feature_id),
    CONSTRAINT plan_features_limit_chk  CHECK (limit_value IS NULL OR limit_value >= 0)
);
CREATE INDEX idx_plan_features_feature ON plan_features (feature_id);

-- Uma assinatura corrente por tenant (histórico fica na auditoria; faturas/cobrança são etapa futura).
CREATE TABLE subscriptions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT       NOT NULL,
    plan_id              BIGINT       NOT NULL,
    status               VARCHAR(10)  NOT NULL,
    started_at           TIMESTAMP(6) NOT NULL,
    current_period_start TIMESTAMP(6),
    current_period_end   TIMESTAMP(6),
    grace_period_end     TIMESTAMP(6),
    canceled_at          TIMESTAMP(6),
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT subscriptions_tenant_fk   FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT subscriptions_plan_fk     FOREIGN KEY (plan_id)   REFERENCES plans(id),
    CONSTRAINT subscriptions_tenant_key  UNIQUE (tenant_id),
    CONSTRAINT subscriptions_status_chk  CHECK (status IN ('ACTIVE', 'PAST_DUE', 'CANCELED')),
    CONSTRAINT subscriptions_period_chk  CHECK (current_period_start IS NULL OR current_period_end IS NULL
                                                OR current_period_end > current_period_start),
    CONSTRAINT subscriptions_grace_chk   CHECK (grace_period_end IS NULL OR current_period_end IS NULL
                                                OR grace_period_end >= current_period_end),
    -- canceled_at preenchido se, e somente se, a assinatura está CANCELED.
    CONSTRAINT subscriptions_canceled_chk CHECK ((status = 'CANCELED') = (canceled_at IS NOT NULL))
);
CREATE INDEX idx_subscriptions_plan ON subscriptions (plan_id);
CREATE INDEX idx_subscriptions_status_period_end ON subscriptions (status, current_period_end);

-- ALLOW/DENY por empresa, independente do plano (contratos personalizados).
CREATE TABLE tenant_feature_overrides (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT       NOT NULL,
    feature_id         BIGINT       NOT NULL,
    effect             VARCHAR(5)   NOT NULL,
    limit_value        BIGINT,
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    updated_by_user_id BIGINT,
    CONSTRAINT tfo_tenant_fk     FOREIGN KEY (tenant_id)          REFERENCES tenants(id),
    CONSTRAINT tfo_feature_fk    FOREIGN KEY (feature_id)         REFERENCES features(id),
    CONSTRAINT tfo_updated_by_fk FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT tfo_unique        UNIQUE (tenant_id, feature_id),
    CONSTRAINT tfo_effect_chk    CHECK (effect IN ('ALLOW', 'DENY')),
    CONSTRAINT tfo_limit_chk     CHECK (limit_value IS NULL OR limit_value >= 0),
    -- DENY nunca carrega limite.
    CONSTRAINT tfo_deny_limit_chk CHECK (effect = 'ALLOW' OR limit_value IS NULL)
);
CREATE INDEX idx_tfo_feature ON tenant_feature_overrides (feature_id);
CREATE INDEX idx_tfo_updated_by ON tenant_feature_overrides (updated_by_user_id);

-- Identidade visual por tenant (PREPARAÇÃO: sem upload nem storage nesta etapa).
-- Só tokens visuais permitidos: cores hexadecimais e uma CHAVE opaca de objeto (nunca binário aqui,
-- nunca CSS/HTML). NULL = usar o padrão do Design System.
CREATE TABLE tenant_branding (
    tenant_id          BIGINT       PRIMARY KEY,
    logo_ref           VARCHAR(255),
    primary_color      VARCHAR(7),
    secondary_color    VARCHAR(7),
    accent_color       VARCHAR(7),
    updated_at         TIMESTAMP(6) NOT NULL,
    updated_by_user_id BIGINT,
    CONSTRAINT tenant_branding_tenant_fk     FOREIGN KEY (tenant_id)          REFERENCES tenants(id),
    CONSTRAINT tenant_branding_updated_by_fk FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT tenant_branding_primary_chk   CHECK (primary_color   IS NULL OR primary_color   ~ '^#[0-9A-F]{6}$'),
    CONSTRAINT tenant_branding_secondary_chk CHECK (secondary_color IS NULL OR secondary_color ~ '^#[0-9A-F]{6}$'),
    CONSTRAINT tenant_branding_accent_chk    CHECK (accent_color    IS NULL OR accent_color    ~ '^#[0-9A-F]{6}$'),
    CONSTRAINT tenant_branding_logo_chk      CHECK (logo_ref IS NULL OR logo_ref ~ '^[A-Za-z0-9][A-Za-z0-9/_.-]{0,254}$')
);
CREATE INDEX idx_tenant_branding_updated_by ON tenant_branding (updated_by_user_id);

-- Catálogo global de funcionalidades comercializáveis (dados de referência, não regras de plano).
INSERT INTO features (code, name, description, kind, active) VALUES
    ('FINANCEIRO',      'Financeiro',           'Despesas, faturas e fluxo de caixa',          'BOOLEAN', TRUE),
    ('EQUIPE',          'Equipe',               'Gestão de equipe e salários',                 'BOOLEAN', TRUE),
    ('RELATORIOS',      'Relatórios',           'Relatórios mensais e oficiais',               'BOOLEAN', TRUE),
    ('PORTFOLIO',       'Portfólio',            'Projetos concluídos e portfólio público',     'BOOLEAN', TRUE),
    ('CUSTOM_DOMAIN',   'Domínio próprio',      'Domínio personalizado da empresa',            'BOOLEAN', TRUE),
    ('CUSTOM_BRANDING', 'Identidade visual',    'Personalização visual completa da empresa',   'BOOLEAN', TRUE),
    ('CUSTOM_LOGO',     'Logo personalizada',   'Logo própria da empresa no ambiente',         'BOOLEAN', TRUE),
    ('CUSTOM_COLORS',   'Cores personalizadas', 'Cores principal, secundária e de destaque',   'BOOLEAN', TRUE),
    ('MAX_USERS',       'Máximo de usuários',   'Limite de usuários ativos da empresa',        'LIMIT',   TRUE),
    ('STORAGE_GB',      'Armazenamento (GB)',   'Limite de armazenamento em GB',               'LIMIT',   TRUE);
