-- V7: financeiro SaaS do Nexus Control Center (Fase 4.4.2): valores contratados, mensalidades e historico de pagamentos.
--
-- CONCEITOS INDEPENDENTES (nunca misturar):
--   plans                = o que o cliente pode contratar (catalogo; NAO tem preco aqui).
--   subscriptions        = vinculo comercial ATUAL tenant <-> plano, agora com os TERMOS CONTRATADOS
--                          (valor, moeda, intervalo, dia de vencimento, carencia) daquele cliente.
--   billing_invoices     = cobranca de UM periodo. Guarda SNAPSHOT do valor e da carencia: mudar o contrato
--                          ou o plano depois NUNCA altera uma cobranca ja emitida.
--   invoice_payments     = historico (append-only por convencao) de eventos financeiros da cobranca.
--   tenants.status       = possibilidade OPERACIONAL de usar o SaaS; tenants.suspension_reason diz POR QUE
--                          esta suspenso (MANUAL x NON_PAYMENT). Cobranca vencida NAO suspende sozinha.
--
-- DINHEIRO: NUMERIC(12,2), nunca float/double. ZERO NAO e permitido (CHECK amount > 0): contrato gratuito ou
-- cortesia e representado por subscriptions.contracted_amount NULL ("nao cobravel" -> nenhuma cobranca e
-- gerada); uma cobranca de valor zero so criaria ruido financeiro e estados ambiguos (paga/aberta?).
--
-- Nenhuma migration anterior (V1-V6) e alterada. Nada e inserido nas tabelas novas.

-- 1) Termos comerciais contratados, na assinatura. Colunas novas com DEFAULT: linhas existentes ficam validas.
ALTER TABLE subscriptions
    ADD COLUMN contracted_amount NUMERIC(12,2),
    ADD COLUMN currency          VARCHAR(3)  NOT NULL DEFAULT 'BRL',
    ADD COLUMN billing_interval  VARCHAR(10) NOT NULL DEFAULT 'MONTHLY',
    ADD COLUMN billing_day       INTEGER     NOT NULL DEFAULT 10,
    ADD COLUMN grace_days        INTEGER     NOT NULL DEFAULT 5;

ALTER TABLE subscriptions
    ADD CONSTRAINT subscriptions_amount_chk     CHECK (contracted_amount IS NULL OR contracted_amount > 0),
    ADD CONSTRAINT subscriptions_currency_chk   CHECK (currency ~ '^[A-Z]{3}$'),
    ADD CONSTRAINT subscriptions_interval_chk   CHECK (billing_interval IN ('MONTHLY')),
    -- 1..28: o dia existe em todos os meses (sem regra de "ultimo dia do mes").
    ADD CONSTRAINT subscriptions_bday_chk       CHECK (billing_day BETWEEN 1 AND 28),
    ADD CONSTRAINT subscriptions_grace_days_chk CHECK (grace_days BETWEEN 0 AND 90),
    -- Permite FK composta (id, tenant_id) de billing_invoices: a cobranca nunca aponta para assinatura de OUTRO tenant.
    ADD CONSTRAINT subscriptions_id_tenant_key  UNIQUE (id, tenant_id);

-- 2) Motivo estruturado da suspensao do tenant (situacao operacional; nao toca em subscription/invoice).
ALTER TABLE tenants
    ADD COLUMN suspension_reason VARCHAR(20),
    ADD COLUMN suspended_at      TIMESTAMP(6);

-- Empresas ja suspensas antes desta versao foram suspensas manualmente (unica forma que existia).
UPDATE tenants SET suspension_reason = 'MANUAL', suspended_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP)
 WHERE status = 'SUSPENSO';

ALTER TABLE tenants
    ADD CONSTRAINT tenants_suspension_reason_chk CHECK (suspension_reason IS NULL OR suspension_reason IN ('MANUAL', 'NON_PAYMENT')),
    -- o motivo so existe enquanto o tenant esta SUSPENSO (a aplicacao sempre o grava ao suspender; SUSPENSO com
    -- motivo nulo = suspensao legada/desconhecida, tratada como MANUAL).
    ADD CONSTRAINT tenants_suspension_state_chk  CHECK (suspension_reason IS NULL OR status = 'SUSPENSO'),
    ADD CONSTRAINT tenants_suspended_at_chk      CHECK ((suspension_reason IS NULL) = (suspended_at IS NULL));

-- 3) Cobrancas.
CREATE TABLE billing_invoices (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT        NOT NULL,
    subscription_id  BIGINT        NOT NULL,
    -- Primeiro dia do mes de competencia (mensal). Um periodo ativo por assinatura (ver indice unico parcial).
    reference_period DATE          NOT NULL,
    amount           NUMERIC(12,2) NOT NULL,
    currency         VARCHAR(3)    NOT NULL,
    due_date         DATE          NOT NULL,
    -- Fim da carencia (inclusive), congelado na emissao: due_date + grace_days da assinatura NAQUELE momento.
    grace_ends_on    DATE          NOT NULL,
    status           VARCHAR(10)   NOT NULL,
    paid_at          TIMESTAMP(6),
    canceled_at      TIMESTAMP(6),
    created_at       TIMESTAMP(6)  NOT NULL,
    updated_at       TIMESTAMP(6)  NOT NULL,
    CONSTRAINT billing_invoices_tenant_fk       FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT billing_invoices_subscription_fk FOREIGN KEY (subscription_id, tenant_id) REFERENCES subscriptions(id, tenant_id),
    -- Permite FK composta de invoice_payments.
    CONSTRAINT billing_invoices_id_tenant_key   UNIQUE (id, tenant_id),
    CONSTRAINT billing_invoices_status_chk      CHECK (status IN ('OPEN', 'PAID', 'OVERDUE', 'CANCELED')),
    CONSTRAINT billing_invoices_amount_chk      CHECK (amount > 0),
    CONSTRAINT billing_invoices_currency_chk    CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT billing_invoices_period_chk      CHECK (EXTRACT(DAY FROM reference_period) = 1),
    CONSTRAINT billing_invoices_grace_chk       CHECK (grace_ends_on >= due_date),
    CONSTRAINT billing_invoices_paid_chk        CHECK ((status = 'PAID') = (paid_at IS NOT NULL)),
    CONSTRAINT billing_invoices_canceled_chk    CHECK ((status = 'CANCELED') = (canceled_at IS NOT NULL))
);
-- Nunca duas mensalidades ATIVAS do mesmo periodo para a mesma assinatura. Uma cobranca CANCELADA nao conta:
-- permite reemitir o periodo corrigido (cancelar + gerar), sem apagar o historico da cancelada.
CREATE UNIQUE INDEX billing_invoices_period_key ON billing_invoices (subscription_id, reference_period)
    WHERE status <> 'CANCELED';
CREATE INDEX idx_billing_invoices_tenant_status ON billing_invoices (tenant_id, status);
CREATE INDEX idx_billing_invoices_status_due    ON billing_invoices (status, due_date);
CREATE INDEX idx_billing_invoices_subscription  ON billing_invoices (subscription_id);

-- 4) Historico de eventos financeiros da cobranca. Nesta etapa so PAYMENT/MANUAL; PIX, cartao, boleto,
-- gateway, estorno e webhook entram AMPLIANDO os CHECKs de kind/method numa migration futura, sem mudar
-- a estrutura. NUNCA armazena dado de cartao; external_ref e so uma referencia opaca (id do comprovante).
CREATE TABLE invoice_payments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id            BIGINT        NOT NULL,
    tenant_id             BIGINT        NOT NULL,
    kind                  VARCHAR(10)   NOT NULL,
    method                VARCHAR(10)   NOT NULL,
    amount                NUMERIC(12,2) NOT NULL,
    currency              VARCHAR(3)    NOT NULL,
    occurred_at           TIMESTAMP(6)  NOT NULL,
    registered_by_user_id BIGINT,
    external_ref          VARCHAR(100),
    created_at            TIMESTAMP(6)  NOT NULL,
    CONSTRAINT invoice_payments_invoice_fk   FOREIGN KEY (invoice_id, tenant_id) REFERENCES billing_invoices(id, tenant_id),
    CONSTRAINT invoice_payments_user_fk      FOREIGN KEY (registered_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT invoice_payments_kind_chk     CHECK (kind IN ('PAYMENT')),
    CONSTRAINT invoice_payments_method_chk   CHECK (method IN ('MANUAL')),
    CONSTRAINT invoice_payments_amount_chk   CHECK (amount > 0),
    CONSTRAINT invoice_payments_currency_chk CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT invoice_payments_ref_chk      CHECK (external_ref IS NULL OR external_ref ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{0,99}$')
);
-- No maximo UM pagamento (kind PAYMENT) por cobranca: barra pagamento duplicado mesmo em corrida.
CREATE UNIQUE INDEX invoice_payments_one_payment_key ON invoice_payments (invoice_id) WHERE kind = 'PAYMENT';
CREATE INDEX idx_invoice_payments_tenant     ON invoice_payments (tenant_id, occurred_at);
CREATE INDEX idx_invoice_payments_occurred   ON invoice_payments (occurred_at);
CREATE INDEX idx_invoice_payments_registered ON invoice_payments (registered_by_user_id);
