-- V8: Modo Suporte (Support Sessions) e observabilidade de erros por tenant (Fase 4.4.3).
--
-- IDENTIDADE: uma Support Session NAO e impersonacao. O ator continua sendo o SUPER_ADMIN real
-- (super_admin_user_id); o tenant e apenas o ALVO/contexto. Nenhum JWT, senha ou usuario do cliente e usado, e
-- users.tenant_id do SUPER_ADMIN nunca muda. A sessao e referenciada por um UUID nao enumeravel (public_id) e so
-- vale para o proprio SUPER_ADMIN autenticado que a criou (verificado a cada requisicao); por isso NAO ha segredo
-- de sessao a armazenar ou vazar.
--
-- TEMPO: sessao de suporte dura 30 min (fixo, sem renovacao; teto rigido de 4 h no CHECK). Elevacao para
-- INTERVENTION vale 10 min a partir de elevated_at (calculado pela aplicacao; depois volta a READ_ONLY efetivo).
--
-- Nenhuma migration anterior (V1-V7) e alterada. Nada e inserido nas tabelas novas.

-- Permite FK composta (id, role): o banco garante que so um usuario SUPER_ADMIN pode ser ator de suporte e que a
-- role dele nao muda enquanto houver sessao registrada.
ALTER TABLE users ADD CONSTRAINT users_id_role_key UNIQUE (id, role);

CREATE TABLE support_sessions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID          NOT NULL,
    super_admin_user_id   BIGINT        NOT NULL,
    super_admin_role      VARCHAR(20)   NOT NULL DEFAULT 'SUPER_ADMIN',
    tenant_id             BIGINT        NOT NULL,
    mode                  VARCHAR(12)   NOT NULL,
    reason                VARCHAR(300)  NOT NULL,
    started_at            TIMESTAMP(6)  NOT NULL,
    expires_at            TIMESTAMP(6)  NOT NULL,
    elevated_at           TIMESTAMP(6),
    elevation_reason      VARCHAR(300),
    ended_at              TIMESTAMP(6),
    request_ip            VARCHAR(64),
    user_agent            VARCHAR(200),
    CONSTRAINT support_sessions_public_id_key UNIQUE (public_id),
    CONSTRAINT support_sessions_user_fk   FOREIGN KEY (super_admin_user_id, super_admin_role) REFERENCES users(id, role),
    CONSTRAINT support_sessions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT support_sessions_role_chk  CHECK (super_admin_role = 'SUPER_ADMIN'),
    CONSTRAINT support_sessions_mode_chk  CHECK (mode IN ('READ_ONLY', 'INTERVENTION')),
    -- Sessao nunca e eterna: expira depois de iniciar e no maximo 4 h depois.
    CONSTRAINT support_sessions_expiry_chk CHECK (expires_at > started_at AND expires_at <= started_at + INTERVAL '4 hours'),
    -- Elevacao explicita: INTERVENTION <=> elevated_at + motivo da intervencao.
    CONSTRAINT support_sessions_elevation_chk CHECK ((mode = 'INTERVENTION') = (elevated_at IS NOT NULL)
                                                    AND (elevated_at IS NULL) = (elevation_reason IS NULL)),
    CONSTRAINT support_sessions_elevated_time_chk CHECK (elevated_at IS NULL OR elevated_at >= started_at),
    CONSTRAINT support_sessions_ended_chk CHECK (ended_at IS NULL OR ended_at >= started_at),
    -- Motivo obrigatorio, limitado, sem caracteres de controle e sem cara de segredo (JWT/Bearer).
    CONSTRAINT support_sessions_reason_chk CHECK (char_length(reason) BETWEEN 10 AND 300
                                                 AND reason !~ '[[:cntrl:]]' AND reason !~* '(bearer +[^ ]|eyj[a-z0-9_-]{10,})'),
    CONSTRAINT support_sessions_elev_reason_chk CHECK (elevation_reason IS NULL OR
                                                 (char_length(elevation_reason) BETWEEN 10 AND 300
                                                  AND elevation_reason !~ '[[:cntrl:]]' AND elevation_reason !~* '(bearer +[^ ]|eyj[a-z0-9_-]{10,})'))
);
-- No maximo UMA sessao ativa (nao encerrada) por SUPER_ADMIN. A aplicacao encerra as expiradas antes de abrir outra.
CREATE UNIQUE INDEX support_sessions_one_active_key ON support_sessions (super_admin_user_id) WHERE ended_at IS NULL;
CREATE INDEX idx_support_sessions_tenant ON support_sessions (tenant_id, started_at DESC);
CREATE INDEX idx_support_sessions_user   ON support_sessions (super_admin_user_id, started_at DESC);

-- Historico protegido: sessao encerrada e imutavel, campos-chave nunca mudam e nada e apagado.
CREATE FUNCTION support_sessions_guard() RETURNS trigger AS $fn$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'support_sessions e historico: exclusao nao permitida';
    END IF;
    IF OLD.ended_at IS NOT NULL THEN
        RAISE EXCEPTION 'support_sessions: sessao encerrada e imutavel';
    END IF;
    IF NEW.id <> OLD.id OR NEW.public_id <> OLD.public_id OR NEW.super_admin_user_id <> OLD.super_admin_user_id
       OR NEW.tenant_id <> OLD.tenant_id OR NEW.reason <> OLD.reason OR NEW.started_at <> OLD.started_at
       OR NEW.expires_at <> OLD.expires_at THEN
        RAISE EXCEPTION 'support_sessions: campos de identidade/tempo sao imutaveis';
    END IF;
    RETURN NEW;
END
$fn$ LANGUAGE plpgsql;
CREATE TRIGGER support_sessions_guard_trg BEFORE UPDATE OR DELETE ON support_sessions
    FOR EACH ROW EXECUTE FUNCTION support_sessions_guard();

-- Eventos de erro da aplicacao (observabilidade). NAO e audit_events: aqui vivem incidentes tecnicos agrupados.
-- Nunca guarda body, query string, headers, cookies, tokens, senha nem stack trace: so metadados seguros.
-- Agrupamento: um registro por (tenant, fingerprint) enquanto NAO resolvido; repeticoes incrementam
-- occurrence_count. Reincidencia depois de resolvido abre um NOVO registro.
CREATE TABLE application_error_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_occurred_at   TIMESTAMP(6)  NOT NULL,
    occurred_at         TIMESTAMP(6)  NOT NULL,
    tenant_id           BIGINT,
    support_session_id  BIGINT,
    user_id             BIGINT,
    correlation_id      VARCHAR(64)   NOT NULL,
    request_method      VARCHAR(10)   NOT NULL,
    request_path        VARCHAR(200)  NOT NULL,
    http_status         INTEGER       NOT NULL,
    error_code          VARCHAR(60)   NOT NULL,
    error_category      VARCHAR(20)   NOT NULL,
    exception_class     VARCHAR(100),
    safe_message        VARCHAR(200)  NOT NULL,
    fingerprint         VARCHAR(64)   NOT NULL,
    occurrence_count    BIGINT        NOT NULL DEFAULT 1,
    resolved_at         TIMESTAMP(6),
    resolved_by_user_id BIGINT,
    CONSTRAINT aee_tenant_fk   FOREIGN KEY (tenant_id)           REFERENCES tenants(id),
    CONSTRAINT aee_session_fk  FOREIGN KEY (support_session_id)  REFERENCES support_sessions(id),
    CONSTRAINT aee_user_fk     FOREIGN KEY (user_id)             REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT aee_resolver_fk FOREIGN KEY (resolved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT aee_category_chk CHECK (error_category IN ('VALIDATION', 'AUTHENTICATION', 'AUTHORIZATION', 'BUSINESS',
                                                          'INTEGRATION', 'DATABASE', 'INTERNAL')),
    CONSTRAINT aee_status_chk   CHECK (http_status BETWEEN 400 AND 599),
    CONSTRAINT aee_count_chk    CHECK (occurrence_count >= 1),
    CONSTRAINT aee_time_chk     CHECK (occurred_at >= first_occurred_at),
    CONSTRAINT aee_fingerprint_chk CHECK (fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT aee_correlation_chk CHECK (correlation_id ~ '^[A-Za-z0-9._-]{8,64}$'),
    CONSTRAINT aee_method_chk   CHECK (request_method ~ '^[A-Z]{3,10}$'),
    -- caminho normalizado: sem query string, fragmento ou espacos.
    CONSTRAINT aee_path_chk     CHECK (request_path ~ '^/[^?#[:space:][:cntrl:]]*$'),
    CONSTRAINT aee_code_chk     CHECK (error_code ~ '^[A-Z][A-Z0-9_]{1,59}$'),
    CONSTRAINT aee_class_chk    CHECK (exception_class IS NULL OR exception_class ~ '^[A-Za-z0-9_.$]{1,100}$'),
    CONSTRAINT aee_message_chk  CHECK (safe_message !~ '[[:cntrl:]]'),
    CONSTRAINT aee_resolved_chk CHECK (resolved_by_user_id IS NULL OR resolved_at IS NOT NULL)
);
-- Um incidente ABERTO por (tenant, fingerprint); tenant nulo (erro sem tenant) agrupa sob 0.
CREATE UNIQUE INDEX aee_open_fingerprint_key ON application_error_events (COALESCE(tenant_id, 0), fingerprint)
    WHERE resolved_at IS NULL;
CREATE INDEX idx_aee_tenant_occurred ON application_error_events (tenant_id, occurred_at DESC);
CREATE INDEX idx_aee_category        ON application_error_events (error_category, occurred_at DESC);
CREATE INDEX idx_aee_occurred        ON application_error_events (occurred_at DESC);
CREATE INDEX idx_aee_fingerprint     ON application_error_events (fingerprint);
CREATE INDEX idx_aee_correlation     ON application_error_events (correlation_id);
CREATE INDEX idx_aee_session         ON application_error_events (support_session_id);
CREATE INDEX idx_aee_user            ON application_error_events (user_id);
CREATE INDEX idx_aee_resolver        ON application_error_events (resolved_by_user_id);
